### ISSUE TITLE
List logos for new Sablier users

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/community-token-list#11]
There are many streams created with the following tokens:

- [x] [$EPOCH](https://ethersca.io/address/0x97D0CfEB4FdE54B430307c9482d6f79C761Fe9B6)
- [x] [$LMR](https://etherscan.io/address/0x4b1D0b9F081468D780Ca1d5d79132b64301085d1)
- [ ] [$KOTOV2](https://etherscan.io/address/0xc75c635c1F5e21D23eC8592Cb37503B82A7EF942)
- [x] [$FLOOR](https://etherscan.io/address/0xf59257E961883636290411c11ec5Ae622d19455e)
- [x] [$NFD](https://etherscan.io/token/0xdfdb7f72c1f195c5951a234e8db9806eb0635346)
- [ ] [$fxA3A](https://polygonscan.com/address/0x58c7b2828e7f2b2caa0cc7feef242fa3196d03df)
- [x] [$UNIT](https://etherscan.io/address/0x1e241521f4767853b376c2fe795a222a07d588ee)

It would be nice if they appeared with a logo on Sablier.

**Comment by PaulRBerg** [comment]
Bump @gavriliumircea - this should be an easy task, but users would appreciate it.

**Comment by gavriliumircea** [comment]
Sorry about that I was caught on with the preparations for the future release

**Comment by PaulRBerg** [comment]
Of course - if you don't have time, feel free to ignore it

**Comment by gavriliumircea** [comment]
I added it for LMR FLOOR and UNIT, I couldn't find any logos for the other.  There are some issues with the ipfs and we are investigating them right now.

**Comment by PaulRBerg** [comment]
Thanks, Mircea - tagging @maxdesalle, could you please reach out to Koto and fxA3A?

For Epoch, you should be able to find the logo here:

https://epochisland.io/

**Comment by maxdesalle** [comment]
Apologies for the wait here, missed this task. I was able to find the $EPOCH and $NFD logos, but failed to find the $fxA3A and $KOTOV2 ones. These tokens only seem to be listed on DEX screeners, and do not have official CoinGecko/CoinMarketCap profiles (or any website with social profile links).

**Comment by PaulRBerg** [comment]
Thanks @maxdesalle, and no worries.

happy to leave two tokens without logos.

Thanks to both of you for your help.
