### ISSUE TITLE
Add XD: XD Token

### ISSUE THREAD

**Issue by 0xluckyg** [sablier-labs/community-token-list#16]
**Please provide the following information for your token.**

- Token Address (HAS to be [checksummed](https://ethsum.netlify.app/)): 0x3005003BDA885deE7c74182e5FE336e9E3Df87bB
- Token Name (from contract): XD Token
- Token Decimals (from contract): 18
- Token Symbol (from contract): XD
- Official project link: https://lenx.finance/
- CoinGecko/CoinMarketCap token page:

**Comment by PaulRBerg** [comment]
Thanks for your request, @0xluckyg.

@gavriliumircea or @maxdesalle, could you handle this, please?

**Comment by maxdesalle** [comment]
Done: [c6608a6](https://github.com/sablier-labs/community-token-list/commit/c6608a63504af2bd0034a9a7b576f0c0d94f80de)
