### ISSUE TITLE
Add ROSA: Rosa

### ISSUE THREAD

**Issue by skeptic-aptitude** [sablier-labs/community-token-list#18]
**Please provide the following information for your token.**

- Token Address (HAS to be [checksummed](https://ethsum.netlify.app/)): 0x6dD51520825b170c32ef322eaDcbd53594929a8a
- Token Name (from contract): Rosa
- Token Decimals (from contract): 18
- Token Symbol (from contract): ROSA
- Official project link: http://rosafinance.io/
- CoinGecko/CoinMarketCap token page: N/A

**Comment by maxdesalle** [comment]
Listed: https://github.com/sablier-labs/community-token-list/commit/62263bd17f6bdb9e862b65ef4d5dfd154bf57529
