### ISSUE TITLE
List logos for PRF and WHIRL

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/community-token-list#22]
Hundreds of streams created with the following tokens:

- [$PRF](https://etherscan.io/token/0xcffcfdada28ab44d5440301470dcd410e75c4765) - Parifi is a long-term Sablier user
- [$WHIRL](https://etherscan.io/address/0xb7037457de15fed6cbecc0c62d5d610834b958ec)
  - See site here: https://whirlprivacy.io

**Comment by maxdesalle** [comment]
Done.
- [a98eac0](https://github.com/sablier-labs/community-token-list/commit/a98eac040e9c76ac6807a841a178193f63eb12c9)
- [15395eb](https://github.com/sablier-labs/community-token-list/commit/15395eb304ad99e5371d9076ad72df38f4ff7dc1)

**Comment by PaulRBerg** [comment]
thank you ser

**Comment by PaulRBerg** [comment]
Re-opening this issue because the logos don't work @maxdesalle @gavriliumircea

<img width="400" alt="SCR-20240131-ovkt" src="https://github.com/sablier-labs/community-token-list/assets/8782666/878ca9b3-2ceb-4357-b4bf-d55f47285be5">

<img width="400" alt="SCR-20240131-ovlk" src="https://github.com/sablier-labs/community-token-list/assets/8782666/0333e85c-e084-4041-a613-143842e1cc86">

**Comment by maxdesalle** [comment]
[Done](https://github.com/sablier-labs/community-token-list/commit/2dafebab8d29e2817075c3acd089d484394b80f3), apologies for that.
