### ISSUE TITLE
List logos for $EMC, $LORDS, and $RVST

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/community-token-list#23]
## Tokens

Lots of streams created with the following tokens:

- [$EMC](https://arbiscan.io/address/0xdfb8be6f8c87f74295a87de951974362cedcfa30)
- [$LORDS](https://etherscan.io/address/0x686f2404e77ab0d9070a46cdfb0b7fecdd2318b0)
- [$RVST](https://etherscan.io/address/0x120a3879da835a5af037bb2d1456bebd6b54d4ba)

## Context

<img width="400" alt="SCR-20240201-mghw" src="https://github.com/sablier-labs/community-token-list/assets/8782666/b9e4d7f8-4caf-40c9-8713-2e9631fa7b2c">

**Comment by PaulRBerg** [comment]
@maxdesalle I've assigned @razgraf and @gavriliumircea because of [this problem](https://github.com/sablier-labs/community-token-list/issues/22#issuecomment-1919264886). Assigning them back now.

**Comment by maxdesalle** [comment]
Got it @PaulRBerg. Have listed the logos for [$EMC](https://github.com/sablier-labs/community-token-list/commit/623a1716a875c5efb29a145a1a2bdfc6caafac9f), [$LORDS](https://github.com/sablier-labs/community-token-list/commit/690b08bda0a87c5d51c967ff7ccd3178edeb4160), and [$RVST](https://github.com/sablier-labs/community-token-list/commit/8cec0f099aca29835313579ceaaaac6ad8ae5181) manually in the meantime.

**Comment by PaulRBerg** [comment]
Can confirm that it works, thanks.
