### ISSUE TITLE
Add EMC: EdgeMatrix Computing Network

### ISSUE THREAD

**Issue by EMCprotocol** [sablier-labs/community-token-list#24]
**Please provide the following information for your token.**

- Token Address (HAS to be [checksummed](https://ethsum.netlify.app/)):0xDFB8BE6F8c87f74295A87de951974362CedCFA30
- Token Name (from contract): EdgeMatrix Computing Network
- Token Decimals (from contract): 18
- Token Symbol (from contract): EMC
- Official project link:https://edgematrix.pro
- CoinGecko/CoinMarketCap token page:

**Comment by maxdesalle** [comment]
[Already done](https://github.com/sablier-labs/community-token-list/commit/623a1716a875c5efb29a145a1a2bdfc6caafac9f) 😉
