### ISSUE TITLE
List token logo for $TREMBLE

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/community-token-list#27]
More than 50 streams created for [$TREMBLE](https://etherscan.io/address/0xde8cd13b812bcd82218754a740b27e76ec1e86ad):

https://app.sablier.com/?t=search&c=1&a=0xde8cd13b812bcd82218754a740b27e76ec1e86ad

**Comment by maxdesalle** [comment]
[Done](https://github.com/sablier-labs/community-token-list/commit/0d96066763057cebaf712c00c908154f962d03c2).
