### ISSUE TITLE
Add VITA-FAST: Molecules of IPNFT #2

### ISSUE THREAD

**Issue by Taliskermalt** [sablier-labs/community-token-list#29]
**Please provide the following information for your token.**

- Token Address (HAS to be [checksummed](https://ethsum.netlify.app/)): 0x6034e0d6999741f07cb6Fb1162cBAA46a1D33d36
- Token Name (from contract): Molecules of IPNFT #2
- Token Decimals (from contract): 18
- Token Symbol (from contract): VITA-FAST
- Official project link:  https://www.vitadao.com/projects/korolchuk-lab
- CoinGecko/CoinMarketCap token page: https://www.coingecko.com/en/coins/molecules-of-korolchuk-ip-nft

**Comment by maxdesalle** [comment]
[Done](https://github.com/sablier-labs/community-token-list/commit/956efc640e1f57411db2f08b7ac7af6f4bbca14f).

**Comment by Taliskermalt** [comment]
You are awesome – thanks so much !

 

Cheers,

 

Todd White
