### ISSUE TITLE
Add primeETH: Prime Staked ETH

### ISSUE THREAD

**Issue by sumpg41** [sablier-labs/community-token-list#30]
**Please provide the following information for your token.**

- Token Address (HAS to be [checksummed](https://ethsum.netlify.app/)): 0x6ef3D766Dfe02Dc4bF04aAe9122EB9A0Ded25615
- Token Name (from contract): Prime Staked ETH
- Token Decimals (from contract): 18
- Token Symbol (from contract): primeETH
- Official project link: https://primestaked.com/
- CoinGecko/CoinMarketCap token page: https://www.coingecko.com/en/coins/prime-staked-eth

**Comment by maxdesalle** [comment]
[Done](https://github.com/sablier-labs/community-token-list/commit/bd83aa477378410cb5e3133973376b9edfae9712).
