### ISSUE TITLE
List $DUEL

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/community-token-list#31]
[We have a lot of $DUEL streams](https://app.sablier.com/?t=search&c=1&a=0x943af2ece93118b973c95c2f698ee9d15002e604).

See:

- https://etherscan.io/address/0x943af2ece93118b973c95c2f698ee9d15002e604
- https://zapper.xyz/token/ethereum/0x943af2ece93118b973c95c2f698ee9d15002e604/DUEL/details

**Comment by maxdesalle** [comment]
[Done](https://github.com/sablier-labs/community-token-list/commit/b2a23f00da76229355a072bd8d9e2e16810ee590).
