### ISSUE TITLE
List $AIUS

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/community-token-list#32]
See [$AIUS](https://etherscan.io/token/0xe3dbc4f88eaa632ddf9708732e2832eeaa6688ab).

<img width="715" alt="SCR-20240215-nwhg" src="https://github.com/sablier-labs/community-token-list/assets/8782666/10013418-4e11-4e86-92a2-537633f2cf37">

**Comment by maxdesalle** [comment]
[Done](https://github.com/sablier-labs/community-token-list/commit/52c85d82e2fc19eb0e36f23ff6792629d82e4bc3).
