### ISSUE TITLE
Add TORQ: Torque

### ISSUE THREAD

**Issue by camconrad** [sablier-labs/community-token-list#34]
**Please provide the following information for your token.**

- Token Address (HAS to be [checksummed](https://ethsum.netlify.app/)): 0xb56C29413AF8778977093B9B4947efEeA7136C36
- Token Name (from contract): Torque
- Token Decimals (from contract): 18
- Token Symbol (from contract): TORQ
- Official project link: https://torque.fi
- CoinGecko/CoinMarketCap token page: https://www.coingecko.com/en/coins/torque

**Comment by camconrad** [comment]
Arbitrum

**Comment by maxdesalle** [comment]
[Done](https://github.com/sablier-labs/community-token-list/commit/29f046508234f0fd3451f4c328d976ccaff61572)!
