### ISSUE TITLE
Add ROSNET : Rosnet

### ISSUE THREAD

**Issue by RosnetAI** [sablier-labs/community-token-list#35]
**Please provide the following information for your token.**

- Token Address (HAS to be [checksummed](https://ethsum.netlify.app/)):
0xd79Bb960Dc8a206806c3a428b31bCA49934d18D7
https://arbiscan.io/token/0xd79Bb960Dc8a206806c3a428b31bCA49934d18D7

- Token Name (from contract):
ROSNET 

- Token Decimals (from contract): 
9

- Token Symbol (from contract):
ROSNET

- Official project link:
https://www.rosnet.ai/

- CoinGecko/CoinMarketCap token page:
https://www.coingecko.com/en/coins/rosnet

**Comment by RosnetAI** [comment]
Hello @maxdesalle.
Just a friendly reminder that we are eagerly awaiting your response.
Regards

**Comment by maxdesalle** [comment]
[Listed](https://github.com/sablier-labs/community-token-list/commit/36d04c16b52df411eeda25cf274b5deafa78dfe9)! FYI you can stream tokens without being listed on our own token list, by manually looking up the contract address in our interface's token selection menu when creating a stream.
