### ISSUE TITLE
List user tokens

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/community-token-list#36]
- [$CHAT](https://etherscan.io/address/0xbb3d7f42c58abd83616ad7c8c72473ee46df2678)
- [$VES](https://etherscan.io/address/0x1f557fb2aa33dce484902695ca1374f413875519)
- [$MONAI](https://etherscan.io/address/0x8c282c35b5e1088bb208991c151182a782637699)
- [$STOS](https://etherscan.io/address/0x08c32b0726c5684024ea6e141c50ade9690bbdcc)

**Comment by maxdesalle** [comment]
Done

**Comment by PaulRBerg** [comment]
ty very much
