### ISSUE TITLE
List new user tokens

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/community-token-list#38]
There are a few dozen streams created with these tokens:

- [DONGO](https://etherscan.io/address/0x8c213ae332274e6314bf4cf989604e7f61162967)
- [DSync](https://etherscan.io/address/0xf94e7d0710709388bce3161c32b4eea56d3f91cc)
- [Reach](https://etherscan.io/address/0x8b12bd54ca9b2311960057c8f3c88013e79316e3)

**Comment by maxdesalle** [comment]
Done!
