### ISSUE TITLE
Add {SALD}: {Salad}

### ISSUE THREAD

**Issue by felixsim** [sablier-labs/community-token-list#39]
**Please provide the following information for your token.**

- Token Address (HAS to be [checksummed](https://ethsum.netlify.app/)): 0x34a62c23261F6a84A40614a68ADDF41943F5d6C6
- Token Name (from contract): Salad
- Token Decimals (from contract): 18
- Token Symbol (from contract): SALD
- Official project link: https://salad.ventures
- CoinGecko/CoinMarketCap token page: https://www.coingecko.com/en/coins/salad

**Comment by razgraf** [comment]
Thank you! Done via https://github.com/sablier-labs/community-token-list/commit/20ce33e2b3578c1e6eb585b49a1aba41f6931eb4.
