### ISSUE TITLE
Add {NEURON}: {CerebrumDAOToken}

### ISSUE THREAD

**Issue by bmagierski** [sablier-labs/community-token-list#40]
**Please provide the following information for your token.**

- Token Address (HAS to be [checksummed](https://ethsum.netlify.app/)): 0xab814ce69E15F6B9660A3B184c0B0C97B9394A6b
- Token Name (from contract): CerebrumDAOToken
- Token Decimals (from contract): 18
- Token Symbol (from contract): NEURON
- Token Icon (e.g. link to png, e.g. 200x200px): 
<img width="375" alt="Cerebrum DAO Icon" src="https://github.com/sablier-labs/community-token-list/assets/6874367/0b389bdb-97df-45d7-9f96-b54ef2585546">
- Chain: Ethereum
- Official project link: https://cerebrumdao.com; https://github.com/bio-xyz/cerebrumdao-token
- CoinGecko/CoinMarketCap token page: Not yet listed. Pre-public listing. Distributing vesting tokens to team

**Comment by razgraf** [comment]
Thank you, the token is now available in the token-list and in the app.

<img width="1074" alt="Screenshot 2024-03-31 at 17 55 04" src="https://github.com/sablier-labs/community-token-list/assets/15740806/b537b838-d19b-424f-ab99-e2916437f9a9">
