### ISSUE TITLE
Add ITP:  Infinite Trading Protocol

### ISSUE THREAD

**Issue by etherpilled** [sablier-labs/community-token-list#41]
**Please provide the following information for your token.**

- Token Address (HAS to be [checksummed](https://ethsum.netlify.app/)): 0x0a7B751FcDBBAA8BB988B9217ad5Fb5cfe7bf7A0
- Token Name (from contract): Infinite Trading Protocol
- Token Decimals (from contract): 18
- Token Symbol (from contract): ITP
- Token Icon (e.g. link to png, e.g. 200x200px): 
![ITP200X200](https://github.com/sablier-labs/community-token-list/assets/49600836/94c25ae3-885c-4d43-89ae-3d9c1cfc9c5a)

- Chain: Optimism
- Official project link: https://www.infinitetrading.io
- CoinGecko/CoinMarketCap token page: Not available yet.

**Comment by razgraf** [comment]
Thanks, resolved in https://github.com/sablier-labs/community-token-list/commit/8549e673865268eccee989b3481e8db3faab85d6.
