### ISSUE TITLE
Add MOLTEN:Molten

### ISSUE THREAD

**Issue by razgraf** [sablier-labs/community-token-list#42]
**Please provide the following information for your token.**

- Token Address (HAS to be [checksummed](https://ethsum.netlify.app/)): 0x66E535e8D2ebf13F49F3D49e5c50395a97C137b1
- Token Name (from contract): Molten
- Token Decimals (from contract): 18
- Token Symbol (from contract): MOLTEN
- Token Icon (e.g. link to png, e.g. 200x200px):
- Chain: Ethereum
- Official project link: https://www.unidex.exchange/molten-network
- CoinGecko/CoinMarketCap token page: https://coinmarketcap.com/currencies/unidex/

**Comment by maxdesalle** [comment]
Done: https://github.com/sablier-labs/community-token-list/commit/fb98336820d3aa6772bc214f4c5ac5adab5cf091
