### ISSUE TITLE
Add MERU: Meru AI

### ISSUE THREAD

**Issue by meruai-dev** [sablier-labs/community-token-list#43]
- Token Address (HAS to be [checksummed](https://ethsum.netlify.app/)): 0x1C610b51B0BccE4A708e2c91d4DDa1f1a8d7e0aD
- Token Name (from contract): https://etherscan.io/address/0x1c610b51b0bcce4a708e2c91d4dda1f1a8d7e0ad
- Token Decimals (from contract): 9 
- Token Symbol (from contract): MERU
- Token Icon (e.g. link to png, e.g. 200x200px): 

![Meru AI](https://github.com/sablier-labs/community-token-list/assets/165311010/927e43d5-4a26-495a-9737-d7166ba2f800)

- Chain: Ethereum 
- Official project link: https://meruai.net/
- CoinGecko/CoinMarketCap token page: N/A

**Comment by maxdesalle** [comment]
Done! https://github.com/sablier-labs/community-token-list/commit/cd185f9033346cd6156fd6e32f580abbd3ec7735

**Comment by meruai-dev** [comment]
@maxdesalle 👋 thank you for getting this done quickly.

Can we please have the CA updated? We had to migrate to a new contract.

```diff
- Token Address (HAS to be [checksummed](https://ethsum.netlify.app/)): 0x1C610b51B0BccE4A708e2c91d4DDa1f1a8d7e0aD
+ Token Address (HAS to be [checksummed](https://ethsum.netlify.app/)): 0x1c9DEeA42E6Fe0900F584c896BceebfcB16bb778
- Token Name (from contract): https://etherscan.io/address/0x1c610b51b0bcce4a708e2c91d4dda1f1a8d7e0ad
+ Token Name (from contract): [Meru AI](https://etherscan.io/token/0x1c9deea42e6fe0900f584c896bceebfcb16bb778)
```

Let me know if I need to make any other changes from my side! TY! ^^

**Comment by maxdesalle** [comment]
Done: https://github.com/sablier-labs/community-token-list/commit/275027f75ad686fe52207b68553cc350a926b9dd

**Comment by meruai-dev** [comment]
Thank you!
