### ISSUE TITLE
Add AUDD: Australian Digital Dollar

### ISSUE THREAD

**Issue by AUDD-digital** [sablier-labs/community-token-list#44]
**Please provide the following information for your token.**

- Token Address 0x4cce605ed955295432958d8951d0b176c10720d5
- Token Name (from contract): AUDD
- Token Decimals (from contract): 6
- Token Symbol (from contract): AUDD
- Token Icon (e.g. link to png, e.g. 200x200px): https://s3.ap-southeast-2.amazonaws.com/static.audd.digital/AUDD-Logo-Blue-512x512px.png
- Chain: Ethereum
- Official project link: https://audd.digital
- CoinGecko/CoinMarketCap token page: https://www.coingecko.com/en/coins/novatti-australian-digital-dollar

**Comment by maxdesalle** [comment]
Done! https://github.com/sablier-labs/community-token-list/commit/c4894e88899d0a56492850193f4f72dcd5610efd
