### ISSUE TITLE
Add {HIGHER}: {higher}

### ISSUE THREAD

**Issue by agaperste** [sablier-labs/community-token-list#47]
**Please provide the following information for your token.**

- Token Address (HAS to be [checksummed](https://ethsum.netlify.app/)): 0x0578d8A44db98B23BF096A382e016e29a5Ce0ffe
- Token Name (from contract): higher
- Token Decimals (from contract): 18
- Token Symbol (from contract): HIGHER
- Token Icon (e.g. link to png, e.g. 200x200px): https://mrtndoteth.notion.site/image/https%3A%2F%2Fprod-files-secure.s3.us-west-2.amazonaws.com%2F07bc14aa-21a1-47c3-a6a9-34662918d87a%2F09448f6f-67b1-474f-bcee-20473329aab3%2F512x512_(1).png?table=block&id=cd8ba1a1-fcdc-4b0c-9633-bb8ddb7f373a&spaceId=07bc14aa-21a1-47c3-a6a9-34662918d87a&width=250&userId=&cache=v2
- Chain: Base
- Official project link: https://www.higher.party/
- CoinGecko/CoinMarketCap token page: https://www.coingecko.com/en/coins/higher

**Comment by maxdesalle** [comment]
https://github.com/sablier-labs/community-token-list/commit/63b4f170cda0e6b5592f193018976acfb499c2f5
