### ISSUE TITLE
Add {TOS}: {Cryptos}

### ISSUE THREAD

**Issue by frankbonnet** [sablier-labs/community-token-list#49]
- Token Addresses: 
https://etherscan.io/address/0x68ccACa9ADF1552B3316d6067690eC27397c8ea8
https://polygonscan.com/address/0x50AA659E6aB263B77d61Ff44cF4A1090141e7111

- Token Name (from contract): Cryptos
- Token Decimals (from contract): 18
- Token Symbol (from contract): TOS
- Token Icon (e.g. link to png, e.g. 200x200px): https://cryptopia.com/downloads/Logo_pack.zip
- Chain: Ethereum and Polygon (OFT)
- Official project link: https://cryptopia.com/
- CoinGecko/CoinMarketCap token page: https://coinmarketcap.com/community/profile/Cryptopia/

**Comment by maxdesalle** [comment]
Done! https://github.com/sablier-labs/community-token-list/commit/568953932b283156275fb010dfba561a7dd7c3fb
