### ISSUE TITLE
List $LLM

### ISSUE THREAD

**Issue by razgraf** [sablier-labs/community-token-list#50]
![app sablier](https://github.com/sablier-labs/community-token-list/assets/15740806/835e70cb-c5b2-4bb7-83c6-76e7129522e6)

Token: [$LLM](https://etherscan.io/token/0x7f5e1a2424ebdd141b0df15f974ddcb87751a012)
Address: `0x7F5E1A2424EBdd141b0Df15F974Ddcb87751A012`
Chain: Ethereum Mainnet
Image: source from [X](https://x.com/LLM_eth)

https://app.sablier.com/stream/LL2-1-20019/

**Comment by maxdesalle** [comment]
Done! https://github.com/sablier-labs/community-token-list/commit/7be345de0d004a66bc878a3e21cb7132b4a0ab43
