### ISSUE TITLE
Add $HACHI: HACHI

### ISSUE THREAD

**Issue by WryRyeRy** [sablier-labs/community-token-list#51]
**Please provide the following information for your token.**
This is the the Arbitrum contract for a bridged token of the pre-existing HACHI token currently listed on Sablier (Ethereum mainnet)

- Token Address (HAS to be [checksummed](https://ethsum.netlify.app/)): 0xF9a76af0bf7a8D4718fb7956a6873eAA64bbD0D9
- Token Name (from contract): HACHI
- Token Decimals (from contract): 18
- Token Symbol (from contract): $HACHI
- Token Icon (e.g. link to png, e.g. 200x200px): https://img.cryptorank.io/coins/akita_dao1675066379563.png
- Chain: Arbitrum
- Official project link: https://akita.network
- CoinGecko/CoinMarketCap token page: https://coinmarketcap.com/currencies/akita-dao/

**Comment by maxdesalle** [comment]
Done! https://github.com/sablier-labs/community-token-list/commit/e5238db8f2850e870c7bdaa2fdbdb1ff4a7843fe

**Comment by WryRyeRy** [comment]
Thank you!

**Comment by WryRyeRy** [comment]
Hi @maxdesalle - 

I've tried to test this token in an Airstream on Arbitrum, in the Sablier app within our SAFE. It does not appear on the community list. I am only able to search for the token by address. 
However, searching by address produces the token, but the URL that is linked to it goes to Etherscan for that contract address, not Arbiscan. Additionally, I do not have the ability to save it to a custom list. 

Here are screenshots, happy to supply any further information:
<img width="381" alt="Screenshot 2024-06-19 at 7 58 27 PM" src="https://github.com/sablier-labs/community-token-list/assets/84806377/3c03073a-a43f-4eed-bdb4-764ecc8b5ecb">
<img width="373" alt="Screenshot 2024-06-19 at 8 03 20 PM" src="https://github.com/sablier-labs/community-token-list/assets/84806377/0e519751-2fe8-4c9c-9be8-f89ec5533ba0">
<img width="346" alt="Screenshot 2024-06-19 at 7 59 04 PM" src="https://github.com/sablier-labs/community-token-list/assets/84806377/7cbd9838-2181-4793-960a-32f0f9c4f909">

Incorrect scanner URL:
https://etherscan.io/token/0xf9a76af0bf7a8d4718fb7956a6873eaa64bbd0d9
Correct scanner URL:
https://arbiscan.io/token/0xF9a76af0bf7a8D4718fb7956a6873eAA64bbD0D9

**Comment by maxdesalle** [comment]
Apologies for that! Had entered the wrong network for HACHI. Should be updated now: https://github.com/sablier-labs/community-token-list/commit/cc9c3b81524ede266576df521c418f6019045095

**Comment by WryRyeRy** [comment]
Thank you so much, worked successfully in the setup of this test.
