### ISSUE TITLE
Add $RWAX: Rwax Token

### ISSUE THREAD

**Issue by SabeloMkhwanzi** [sablier-labs/community-token-list#52]
**Please provide the following information for your token.**
This token represent RWAX token which is the protocol utility token of RWAX ecosystem
- Token Address (HAS to be [checksummed](https://ethsum.netlify.app/)): [0xe0023E73aab4fE9a22f059a9d27E857E027eE3dc](https://basescan.org/address/0xe0023e73aab4fe9a22f059a9d27e857e027ee3dc)
- Token Name (from contract): [Rwax Token](https://basescan.org/token/0xe0023e73aab4fe9a22f059a9d27e857e027ee3dc)
- Token Decimals (from contract): 18
- Token Symbol (from contract): RWAX
- Token Icon (e.g. link to png, e.g. 200x200px): https://i.ibb.co/W5BxqVq/Rwax-token.png
- Chain: Base 
- Official project link: https://therwax.com/

**Comment by maxdesalle** [comment]
Done! https://github.com/sablier-labs/community-token-list/commit/344a86d133d990921f7bae43a711abe46aae7b0b
