### ISSUE TITLE
Add {VITARNA}: {VitaDAO - ArtanBIO IP Tokens}

### ISSUE THREAD

**Issue by Taliskermalt** [sablier-labs/community-token-list#53]
**Please provide the following information for your token.**

- Token Address (HAS to be [checksummed](https://ethsum.netlify.app/)): 0x7b66E84Be78772a3afAF5ba8c1993a1B5D05F9C2
- Token Name (from contract): IP Tokens of IPNFT #28
- Token Decimals (from contract):18
- Token Symbol (from contract):VITARNA
- Token Icon (e.g. link to png, e.g. 200x200px): 
- Chain: 1
- Official project link: vitarna.xyz
- CoinGecko/CoinMarketCap token page:

**Comment by maxdesalle** [comment]
Listed! Let me know if you want us to add a logo. https://github.com/sablier-labs/community-token-list/commit/b0dd48f073308072b0a64c8d255f01fb24f60766

**Comment by Taliskermalt** [comment]
Thanks Maxime!We're still working on the logo.Cheers,ToddSent from my Galaxy
-------- Original message --------From: Maxime Desalle ***@***.***> Date: 2024-06-06  11:40  (GMT-05:00) To: sablier-labs/community-token-list ***@***.***> Cc: Todd White ***@***.***>, Author ***@***.***> Subject: Re: [sablier-labs/community-token-list] Add {VITARNA}: {VitaDAO - ArtanBIO IP Tokens} (Issue #53) 
Listed! Let me know if you want us to add a logo. b0dd48f

**Comment by Taliskermalt** [comment]
Hello Maxime,

 

Logo attached.

 

Cheers,

 

Todd

**Comment by maxdesalle** [comment]
Hey @Taliskermalt I think that because you answered via email, it's not possible for me to see the attachment in here. Could you please send over a link to the logo, or alternatively directly respond on GitHub as opposed to via email? Thank you.
