### ISSUE TITLE
Add {EAVE}: {EaveAI}

### ISSUE THREAD

**Issue by RoseBabaganoush** [sablier-labs/community-token-list#54]
**Please provide the following information for your token.**

- Token Address (HAS to be [checksummed](https://ethsum.netlify.app/)): 0x974D796E0Bea47038f39C3F98b1aA2c5240b5495
- Token Name (from contract): EaveAI
- Token Decimals (from contract): 18
- Token Symbol (from contract): EAVE
- Token Icon (e.g. link to png, e.g. 200x200px): https://framerusercontent.com/images/yt1KFWTwIz7dDmDnVyzaZlu5bnU.png
- Chain: ETH
- Official project link: https://www.eaveai.xyz/
- CoinGecko/CoinMarketCap token page:

**Comment by maxdesalle** [comment]
Listed! https://github.com/sablier-labs/community-token-list/commit/4584c4486db82bd9b0181259944a5bc09a9ad54d
