### ISSUE TITLE
Add {NAI}: {Nuklai}

### ISSUE THREAD

**Issue by razgraf** [sablier-labs/community-token-list#55]
**Please provide the following information for your token.**

- Token Address (HAS to be [checksummed](https://ethsum.netlify.app/)): https://snowtrace.io/token/0x5ac34c53a04b9aaa0bf047e7291fb4e8a48f2a18
- Token Name (from contract): Nuklai Token
- Token Decimals (from contract): 18
- Token Symbol (from contract): NAI
- Token Icon (e.g. link to png, e.g. 200x200px):
- Chain: Avalanche
- CoinGecko/CoinMarketCap token page: https://www.coingecko.com/en/coins/nuklai
- Stream: http://localhost:4001/stream/LD2-43114-1178/

**Comment by maxdesalle** [comment]
Done! https://github.com/sablier-labs/community-token-list/commit/ef6dcfe74c65e2843d32c3dad7b074b27aed0f1f
