### ISSUE TITLE
Add XEON: Xeon Protocol

### ISSUE THREAD

**Issue by heyJonBray** [sablier-labs/community-token-list#57]
**Please provide the following information for your token.**

- Token Address (HAS to be [checksummed](https://ethsum.netlify.app/)): 0x8d65a2eaBDE4B31cbD7E43F27E47559d1CCec86c
- Token Name (from contract): Xeon Protocol
- Token Decimals (from contract): 9
- Token Symbol (from contract): XEON
- Token Icon (e.g. link to png, e.g. 200x200px): https://aquamarine-evil-bedbug-307.mypinata.cloud/ipfs/QmXGv9a49w7hNV5TPsk2BdBw2oFHbNFvKWyMSFscUN6VLQ
- Chain: Ethereum
- Official project link: https://xeon-protocol.io/

CoinGecko/CoinMarketCap token page is being added currently. We just launched the token today and need to set up a stream for our vesting.

**Comment by maxdesalle** [comment]
Done! https://github.com/sablier-labs/community-token-list/commit/a4c27d6fe6778cdc06b2d98b7ecb15869ba3b108
