### ISSUE TITLE
Add MUL: Multipool

### ISSUE THREAD

**Issue by shizong888** [sablier-labs/community-token-list#58]
**Please provide the following information for your token.**

- Token Address (HAS to be [checksummed](https://ethsum.netlify.app/)): 0x9eF3da23C304d88F856F2928B0BE17D9F5d0752F
- Token Name (from contract): Multipool
- Token Decimals (from contract): 18
- Token Symbol (from contract): MUL
- Token Icon (e.g. link to png, e.g. 200x200px): https://i.imgur.com/L3scNRg.png
- Chain: Ethereum
- Official project link: https://multipool.finance
- CoinGecko/CoinMarketCap token page: https://www.coingecko.com/en/coins/multipool

**Comment by maxdesalle** [comment]
Done! https://github.com/sablier-labs/community-token-list/commit/8e1fea6d92f42121586b836cec243f2f95433741
