### ISSUE TITLE
Add OMNI: Omni Network

### ISSUE THREAD

**Issue by fabtreb** [sablier-labs/community-token-list#60]
**Please provide the following information for your token.**

- Token Address (HAS to be [checksummed](https://ethsum.netlify.app/)): 0x36E66fbBce51e4cD5bd3C62B637Eb411b18949D4
- Token Name (from contract): Omni Network
- Token Decimals (from contract): 18
- Token Symbol (from contract): OMNI 
- Token Icon (e.g. link to png, e.g. 200x200px): https://assets.coingecko.com/coins/images/36465/standard/Symbol-Color.png
- Chain: 1
- Official project link: https://omni.network/
- CoinGecko/CoinMarketCap token page:  https://www.coingecko.com/en/coins/omni-network

See PR
https://github.com/sablier-labs/community-token-list/pull/59/files

**Comment by maxdesalle** [comment]
https://github.com/sablier-labs/community-token-list/commit/2e25e1c634e3d7425e05cb5df5d3128076ec26af
