### ISSUE TITLE
how to add a network's native token to your list? 

### ISSUE THREAD

**Issue by GiupiDeLuca** [sablier-labs/community-token-list#63]
hi, I was going to add $IOTX token to the token list. However, [IoTeX](https://iotex.io/) is an EVM layer 1 which has it's own native token just like $ETH. How do we handle adding a native token to the Sablier token list in this case? thank you!

**Comment by maxdesalle** [comment]
Hey @GiupiDeLuca! Given we do not support IoTeX in our user interface, it's probably only useful to list a wrapped version of it on the network of your choice, like Ethereum, for example. Feel free to submit a pull request for it, let me know if you need any help!
