### ISSUE TITLE
May I ask if you support other EVM-compatible L1 chains?

### ISSUE THREAD

**Issue by huangzhiran** [sablier-labs/community-token-list#64]

**Comment by maxdesalle** [comment]
Hey! You can find all supported chains [here](https://docs.sablier.com/contracts/v2/deployments).

**Comment by raullenchai** [comment]
@maxdesalle - how can we get IoTeX L1 (evm-compatible) supported? This is ask from our investors. Let us know, thx.

**Comment by maxdesalle** [comment]
Hey @raullenchai, could you please DM me on Telegram (@maxdesalle)? Will create a chat.
