### ISSUE TITLE
Write weekly CI that checks that all tokens have the correct number of decimals

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/community-token-list#67]
This isn't trivial to implement, but it would be very much worth it to do it — we should write a weekly CI test that checks that all tokens have the correct number of decimals. We should use the Infura API for this (open to recommendations if there's something better out there).
 
The goal is to prevent accidental listings whereby the token's decimals does not correspond to the actual value.

**Comment by smol-ninja** [comment]
> We should use the Etherscan API for this

Did you mean alchemy / infura API?

**Comment by smol-ninja** [comment]
@maxdesalle I see that we have listed [0x416494bD4FbEe227313b76a07A1e859928D7bA47](https://snowtrace.io/address/0x416494bD4FbEe227313b76a07A1e859928D7bA47/contract/43114/code) in [avalanche-mainnet.json](https://github.com/sablier-labs/community-token-list/blob/main/src/tokens/avalanche-mainnet.json#L163) but its not an ERC20 token. I couldn't find a relevant issue as well.

Should I remove it?

**Comment by maxdesalle** [comment]
Looks like it was listed before we migrated to the Tokenlist format @smol-ninja so not sure about the context here either, from looking the contract and the token name it seems to be an ERC-20 representation of funds stored in a staking contract? Though as you rightfully mentioned the contract address doesn't seem to be a token, so I think we should be good to remove it. Thanks for catching that!

**Comment by smol-ninja** [comment]
> it seems to be an ERC-20 representation of funds stored in a staking contract

It does not inherit from ERC20 contract. Its just a staking contract. I am going to create a new PR to close this issue and will remove the invalid address as well. I have found several other errors in decimals value.

**Comment by PaulRBerg** [comment]
nice one @smol-ninja
