### ISSUE TITLE
Add {COIM}: {CoinMath}

### ISSUE THREAD

**Issue by bekovrafik** [sablier-labs/community-token-list#68]
**Please provide the following information for your token.**

- Token Address (HAS to be [checksummed](https://ethsum.netlify.app/)): 0xd2237d9fe0c36721220e4bd88aa85b55ffda0e84
- Token Name (from contract): CoinMath
- Token Decimals (from contract): 8
- Token Symbol (from contract): COIM
- Token Icon (e.g. link to png, e.g. 200x200px): https://raw.githubusercontent.com/CoinMath/COIM/refs/heads/main/assets/images/CoinMath-Logo.png
- Chain: Base
- Official project link: https://coinmath.org
- CoinGecko/CoinMarketCap token page: https://coinmarketcap.com/dexscan/base/0xf4ce3fa58c525689abada68a13834b8cef192868/

**Comment by maxdesalle** [comment]
Listed! https://github.com/sablier-labs/community-token-list/commit/961756a4e4d9d572ce5f6766a527b678ce2fbf14
