### ISSUE TITLE
Add Data Lake Token: LAKE

### ISSUE THREAD

**Issue by os-dlake** [sablier-labs/community-token-list#70]
**Please provide the following information for your token.**

- Token Address (HAS to be [checksummed](https://ethsum.netlify.app/)): 0xf9ca9523e5b5a42c3018c62b084db8543478c400
- Token Name (from contract): Data Lake Token
- Token Decimals (from contract): 18
- Token Symbol (from contract): LAKE
- Token Icon (e.g. link to png, e.g. 200x200px): https://assets.coingecko.com/coins/images/29279/standard/VWlCfLlX_400x400.jpeg
- Chain: Ethereum
- Official project link: https://data-lake.co/
- CoinGecko/CoinMarketCap token page: https://www.coingecko.com/en/coins/data-lake

**Comment by maxdesalle** [comment]
Listed! https://github.com/sablier-labs/community-token-list/commit/d3fe4a5afb80b20614a08e0af0353b89b2e29f8a
