### ISSUE TITLE
Add sUSDS: Savings USDS

### ISSUE THREAD

**Issue by gosuto-inzasheru** [sablier-labs/community-token-list#72]
**Please provide the following information for your token.**

- Token Address (**HAS** to be [checksummed](https://ethsum.netlify.app/)): `0xa3931d71877C0E7a3148CB7Eb4463524FEc27fbD`
- Token Name (from contract): `Savings USDS`
- Token Decimals (from contract): `18`
- Token Symbol (from contract): `sUSDS`
- Token Icon (**HAS** to be in PNG, under 200x200): `https://etherscan.io/token/images/skysUSDSCoin_32.png`
- Chain: `1 (Ethereum)`
- Official project link: `https://sky.money/`
- CoinGecko/CoinMarketCap token page: `N/A`

**Comment by maxdesalle** [comment]
Listed! https://github.com/sablier-labs/community-token-list/commit/e59b04fcbddcf7e79485a973b07a4bb5ff2c1e38
