### ISSUE TITLE
Add {0x82AF3812418D2c60A5e41093dE5D5130e895b3e8}: {MIKA}

### ISSUE THREAD

**Issue by swervehoe** [sablier-labs/community-token-list#73]
**Please provide the following information for your token.**
This token is for testing purposes for Metaverse HQ

- Token Address (**HAS** to be [checksummed](https://ethsum.netlify.app/)): 0x82AF3812418D2c60A5e41093dE5D5130e895b3e8
- Token Name (from contract): MIKA
- Token Decimals (from contract): 18
- Token Symbol (from contract): $MIKA
- Token Icon (**HAS** to be in PNG, under 200x200): https://pbs.twimg.com/profile_images/1612877061135208452/F66uwEds_400x400.jpg
- Chain: Sepolia ETH
- Official project link: https://app.mvhq.io
- CoinGecko/CoinMarketCap token page:

**Comment by PaulRBerg** [comment]
Thank you for your request. Listed now:

https://github.com/sablier-labs/community-token-list/commit/b60b6a61d22d8035b3c4b31efd875570cf3c017c
