### ISSUE TITLE
Add {TRIBL}: {Tribal Finance}

### ISSUE THREAD

**Issue by tribalfinance** [sablier-labs/community-token-list#75]
**Please provide the following information for your token.**

- Token Address (**HAS** to be [checksummed](https://ethsum.netlify.app/)): 0x6988A804C74Fd04F37DA1EA4781CEa68c9C00F86
- Token Name (from contract): Tribal Token
- Token Decimals (from contract): 18
- Token Symbol (from contract): TRIBL
- Token Icon (**HAS** to be in PNG, under 200x200): https://etherscan.io/token/images/tribaltoken_32.png
- Chain: Ethereum
- Official project link: https://tribal.finance/
- CoinGecko/CoinMarketCap token page: https://coinmarketcap.com/currencies/tribal-token/

**Comment by maxdesalle** [comment]
Listed! https://github.com/sablier-labs/community-token-list/commit/212cba6216819b86940afa8dd4881d7cee9700e0
