### ISSUE TITLE
Add NAYM: Naym

### ISSUE THREAD

**Issue by tgeorgas** [sablier-labs/community-token-list#76]
**Please provide the following information for your token.**

- Token Address (**HAS** to be [checksummed](https://ethsum.netlify.app/)): 0x314d7f9e2f55B430ef656FBB98A7635D43a2261E
- Token Name (from contract): NAYM
- Token Decimals (from contract): 18
- Token Symbol (from contract): Naym
- Token Icon (**HAS** to be in PNG, under 200x200):
- Chain: Base
- Official project link: https://www.naymtoken.com/
- CoinGecko/CoinMarketCap token page: NA
![NAYMLogo (2)](https://github.com/user-attachments/assets/fbeea6dc-590c-4b88-b7b1-d755850a2272)

**Comment by maxdesalle** [comment]
Listed! Should be live on the interface shortly. https://github.com/sablier-labs/community-token-list/commit/37158590a80f232140271ee432d471d248e82754
