### ISSUE TITLE
Add REG : RealToken Ecosystem Governance

### ISSUE THREAD

**Issue by Michael-RealT** [sablier-labs/community-token-list#77]
**Please provide the following information for your token.**

- Token Address (**HAS** to be [checksummed](https://ethsum.netlify.app/)): 0x0AA1e96D2a46Ec6beB2923dE1E61Addf5F5f1dce
- Token Name (from contract): RealToken Ecosystem Governance
- Token Decimals (from contract): 18
- Token Symbol (from contract): REG
- Token Icon (**HAS** to be in PNG, under 200x200): 
![REG_Logo_200x200](https://github.com/user-attachments/assets/6a7a4726-8f51-4444-b8e5-c6b9c98af882)

- Chain: Gnosis, Ethereum, Polygon
- Official project link: https://forum.realtoken.community/
- CoinGecko/CoinMarketCap token page: https://www.coingecko.com/en/coins/realtoken-ecosystem-governance

**Comment by maxdesalle** [comment]
Listed! https://github.com/sablier-labs/community-token-list/commit/c62fe5cd5d4cc83cc9d08fe80be691a1b7414fb8
