### ISSUE TITLE
Add ⌘: NANI

### ISSUE THREAD

**Issue by z0r0z** [sablier-labs/community-token-list#79]
- Token Address: 0x00000000000007C8612bA63Df8DdEfD9E6077c97
- Token Name (from contract): NANI
- Token Decimals (from contract): 18
- Token Symbol (from contract): ⌘
- Token Icon: https://content.wrappr.wtf/ipfs/QmZNDkY14fUiEixQZNwBw2tWzpXYyLQttLSGdRsezo3vRL
- Chain: 1
- Official project link: https://nani.ooo/
- CoinGecko/CoinMarketCap token page: N/A

**Comment by maxdesalle** [comment]
Listed! https://github.com/sablier-labs/community-token-list/commit/e6140cc791b3210d8a0ff5fa64bfbcb05fe774f7
