### ISSUE TITLE
Add {NHT}: {Neighbourhoods}

### ISSUE THREAD

**Issue by sidsthalekar** [sablier-labs/community-token-list#81]
**Please provide the following information for your token.**

- Token Address (**HAS** to be [checksummed](https://ethsum.netlify.app/)): 0x84342e932797FC62814189f01F0Fb05F52519708
- Token Name (from contract): Neighbourhoods
- Token Decimals (from contract): 18
- Token Symbol (from contract): NHT
- Token Icon (**HAS** to be in PNG, under 200x200): 
![logo_gitbook](https://github.com/user-attachments/assets/a526df15-1910-4086-9f97-3b9638f41a1a)

- Chain: Ethereum Mainnet, Polygon
- Official project link: https://neighbourhoods.network
- CoinGecko/CoinMarketCap token page: https://coinmarketcap.com/currencies/neighbourhoods/

**Comment by maxdesalle** [comment]
Listed! https://github.com/sablier-labs/community-token-list/commit/40a0efb577d085913fb05a5a5adb27832e1949a6
