### ISSUE TITLE
Add {VIS}: {Envision Labs}

### ISSUE THREAD

**Issue by Envision-Miles** [sablier-labs/community-token-list#83]
**Please provide the following information for your token.**

- Token Address (**HAS** to be [checksummed](https://ethsum.netlify.app/)): 0xFc60AA1fFCA50Ce08b3cDeC9626c0Bb9E9b09BeC
- Token Name (from contract): Envision
- Token Decimals (from contract): 18
- Token Symbol (from contract): VIS
- Token Icon (**HAS** to be in PNG, under 200x200): https://about.envisionlabs.io/media/pages/Envision-Logo.png
- Chain: Base
- Official project link: https://envisionlabs.io/
- CoinGecko/CoinMarketCap token page: https://www.coingecko.com/en/coins/envision-labs

**Comment by maxdesalle** [comment]
Already listed! https://github.com/sablier-labs/community-token-list/commit/cf5a8f56d0526fc1bd6ed42d08b0597df41a6a69
