### ISSUE TITLE
Add sDAI: Savings xDAI

### ISSUE THREAD

**Issue by xdecentralix** [sablier-labs/community-token-list#85]
**Please provide the following information for your token.**

- Token Address (**HAS** to be [checksummed](https://ethsum.netlify.app/)): 0xaf204776c7245bF4147c2612BF6e5972Ee483701
- Token Name (from contract): Savings xDAI
- Token Decimals (from contract): 18
- Token Symbol (from contract): sDAI
- Token Icon (**HAS** to be in PNG, under 200x200): https://assets.coingecko.com/coins/images/32066/standard/sDAI_Logo_%281%29.png
- Chain: Gnosis Chain (ID 100)
- Official project link: https://app.spark.fi/
- CoinGecko/CoinMarketCap token page: https://www.coingecko.com/en/coins/savings-xdai

**Comment by maxdesalle** [comment]
Listed!
