### ISSUE TITLE
Add REWARD: Rewardable

### ISSUE THREAD

**Issue by artiffine-vojtech** [sablier-labs/community-token-list#86]
https://basescan.org/address/0x1986Cc18D8eC757447254310D2604f85741aA732

**Please provide the following information for your token.**

- Token Address (**HAS** to be [checksummed](https://ethsum.netlify.app/)): 0x1986Cc18D8eC757447254310D2604f85741aA732
- Token Name (from contract): Rewardable
- Token Decimals (from contract): 18
- Token Symbol (from contract): REWARD
- Token Icon (**HAS** to be in PNG, under 200x200): https://ibb.co/0JFPGRR
- Chain: Base
- Official project link: https://www.rewardable.app/
- CoinGecko/CoinMarketCap token page: https://www.coingecko.com/en/coins/rewardable

**Comment by maxdesalle** [comment]
Listed! https://github.com/sablier-labs/community-token-list/commit/877f3525a65cb59a0cdb34bc69086e3cd1f97bd3
