### ISSUE TITLE
Add superOETHb: Super OETH

### ISSUE THREAD

**Issue by sumpg41** [sablier-labs/community-token-list#88]
**Please provide the following information for your token.**

- Token Address (**HAS** to be [checksummed](https://ethsum.netlify.app/)): 0xDBFeFD2e8460a6Ee4955A68582F85708BAEA60A3
- Token Name (from contract): Super OETH
- Token Decimals (from contract): 18
- Token Symbol (from contract): superOETHb
- Token Icon (**HAS** to be in PNG, under 200x200): https://github.com/OriginProtocol/origin-website/blob/master/static/img/coins/superoeth-200x200.png
- Chain: Base
- Official project link: https://www.originprotocol.com/super-oeth
- CoinGecko/CoinMarketCap token page: https://www.coingecko.com/en/coins/super-oeth

**Comment by maxdesalle** [comment]
Listed! https://github.com/sablier-labs/community-token-list/commit/fd0cf0b14cfd3c5ffa493c42f7f547a86e682a4a
