### ISSUE TITLE
Add ZRS: Zaros Finance

### ISSUE THREAD

**Issue by pedrobergamini** [sablier-labs/community-token-list#90]
**Please provide the following information for your token.**

- Token Address (**HAS** to be [checksummed](https://ethsum.netlify.app/)): 0x75e88B8c2d34a52a6d36deAda664D7dc9116e4EF
- Token Name (from contract): Zaros Finance
- Token Decimals (from contract): 18
- Token Symbol (from contract): ZRS
- Token Icon (**HAS** to be in PNG, under 200x200): https://assets.coingecko.com/coins/images/37060/standard/zrs.png?1713175430
- Chain: Ethereum
- Official project link: https://zaros.fi
- CoinGecko/CoinMarketCap token page: https://www.coingecko.com/en/coins/zaros

**Comment by maxdesalle** [comment]
Listed! https://github.com/sablier-labs/community-token-list/commit/2d6c30cda912ea2d96efd3f2114fbf9d168ecefe
