### ISSUE TITLE
Add {TOKEN_SYMBOL}: {TOKEN_NAME}

### ISSUE THREAD

**Issue by Racfathers** [sablier-labs/community-token-list#91]
**Please provide the following information for your token.**

- Token Address (**HAS** to be [checksummed](https://ethsum.netlify.app/)):
- Token Name (from contract): fun Consigliere(RAZZ)
- Token Decimals (from contract): 0x4B69EA52F8cb02b53613Fa1E24F2579176C44C57
- Token Symbol (from contract): RAZZ
- Token Icon (**HAS** to be in PNG, under 200x200):
- Chain:Base
- Official project link:www.racfathers.com
- CoinGecko/CoinMarketCap token page:
![Consigliere](https://github.com/user-attachments/assets/a84be14d-9d7f-44c0-8c0e-eaf7c64e69ea)

**Comment by maxdesalle** [comment]
Listed! https://github.com/sablier-labs/community-token-list/commit/77e4e2ed26a62f869b8e44e720ab8bac50011434
