### ISSUE TITLE
Add ANZ: Anzen

### ISSUE THREAD

**Issue by bshyong** [sablier-labs/community-token-list#92]
**Please provide the following information for your token.**

- Token Address (**HAS** to be [checksummed](https://ethsum.netlify.app/)): 0xeeC468333ccc16D4BF1cEf497A56cf8C0aAe4Ca3
- Token Name (from contract): Anzen
- Token Decimals (from contract): 18
- Token Symbol (from contract): ANZ
- Token Icon (**HAS** to be in PNG, under 200x200): https://anzen.finance/anz-token-200px.png
- Chain: Base
- Official project link: https://anzen.finance/
- CoinGecko/CoinMarketCap token page: https://www.coingecko.com/en/coins/anzen-finance

**Comment by maxdesalle** [comment]
Listed! https://github.com/sablier-labs/community-token-list/commit/5c8c047ecc1d844c178e699a5c32d14166fff981
