### ISSUE TITLE
Add $BRAINS: $BRAINS - your greed is my fuel 🤯🧠 by Virtuals

### ISSUE THREAD

**Issue by mariusSil** [sablier-labs/community-token-list#94]
**Please provide the following information for your token.**

- Token Address (**HAS** to be [checksummed](https://ethsum.netlify.app/)): 0xF25B7DD973e30Dcf219fbED7bD336b9ab5A05DD9
- Token Name (from contract): $BRAINS - your greed is my fuel 🤯🧠 by Virtuals
- Token Decimals (from contract): 18
- Token Symbol (from contract): $BRAINS
- Token Icon (**HAS** to be in PNG, under 200x200):
- Chain: Base
- Official project link: https://hailbrains.com
- CoinGecko/CoinMarketCap token page: https://www.geckoterminal.com/base/pools/0xfb6a142dc2fb922130027c135326e165fe1a039c?utm_source=coingecko&utm_medium=referral&utm_campaign=searchresults
**Please provide the following information for your token.**

**Comment by maxdesalle** [comment]
Listed! https://github.com/sablier-labs/community-token-list/commit/1217d4587179f2c776d546d3fdb538934ddabbba
