### ISSUE TITLE
Add BEAVER: Beaver Coin

### ISSUE THREAD

**Issue by LucasOCB** [sablier-labs/community-token-list#96]
- Token Address (**HAS** to be [checksummed](https://ethsum.netlify.app/)): 0x880A3Ae90f989030708A529ABd841589053c1dC2
- Token Name (from contract): Beaver Coin
- Token Decimals (from contract): 18
- Token Symbol (from contract): BEAVER
- Token Icon (**HAS** to be in PNG, under 200x200): https://beaver-coin.xyz/imgs/Memecoin_Oficial.png
- Chain: Linea
- Official project link: https://beaver-coin.xyz/
- CoinGecko/CoinMarketCap token page: https://dexscreener.com/linea/0x8b5603b539973545dc743f5658a68a33a41e234c

**Comment by maxdesalle** [comment]
Listed! https://github.com/sablier-labs/community-token-list/commit/c4672887fe24f540ad33677ac79907beb36b01a1
