### ISSUE TITLE
Add GX: Grindery X

### ISSUE THREAD

**Issue by gilgimenez** [sablier-labs/community-token-list#97]
**Please provide the following information for your token.**

- Token Address (**HAS** to be [checksummed](https://ethsum.netlify.app/)): https://polygonscan.com/token/0x8730762cad4a27816a467fac54e3dd1e2e9617a1
https://etherscan.io/token/0x8730762Cad4a27816A467fAc54e3dd1E2e9617A1
- Token Name (from contract): Grindery X 
- Token Decimals (from contract): 18
- Token Symbol (from contract): GX
- Token Icon (**HAS** to be in PNG, under 200x200):
https://drive.google.com/file/d/161TOO3hDIBOGwetXxjQ4xwtXHchR_jIW/view?usp=sharing
- Chain: 
Ethereum and Polygon 
- Official project link: 
https://docs.grindery.com/
- CoinGecko/CoinMarketCap token page: Not Listed yet -process on going-

**Comment by maxdesalle** [comment]
Listed! https://github.com/sablier-labs/community-token-list/commit/80f4a6d9a637ba01462db8d41901309e5cb80d13

**Comment by gilgimenez** [comment]
Thanks
